services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=hexadeventure'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=test'
    ports:
      - '27017:27017'

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_ROOT_PASSWORD=test'
      - 'MYSQL_DATABASE=hexadeventure'
    ports:
      - '3306:3306'

  postgres:
    image: 'postgres:17-alpine'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=test'
      - 'POSTGRES_DB=hexadeventure'
    ports:
      - '5432:5432'